### ISSUE TITLE
数据集链接打不开

### ISSUE THREAD

**Issue by wengwenchao123** [zachysun/Taxi_Traffic_Benchmark#1]
你好，请问数据集现在是有问题吗，我这边点击后一直显示服务器有问题

**Comment by zachysun** [comment]
好像是这个团队不再提供了，我是之前下载的

**Comment by wengwenchao123** [comment]
啊，那是不是这个文章没法复现了（笑哭）

**Comment by zachysun** [comment]
复现的话可以直接使用这个仓库提供的'/data/'，里面是加工后的数据。
GPS轨迹数据集公开的确实不多，你可以看看T-Drive，这个还是公开的。
轨迹数据用的最多的好像是滴滴盖亚的数据集，但是也不公开了🤣。
交通预测的话你用过的PEMS就足够了吧，我是课题要求才使用的轨迹数据🤣 ，但其实我也是将原数据集加工成了类似PEMS以及BJTaxi的形式。
